### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-1-infografia-JoseABCruz#2]
José Antonio Balbuena Cruz

**Comment by JoseABCruz** [comment]
[ciclo de vida del software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-JoseABCruz/files/9420107/ciclo.de.vida.del.software.pdf)

**Comment by abicoronel** [comment]
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
